package calculadora;

//@author tata7
public class PorTres extends javax.swing.JFrame {

    public PorTres() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    Ejecutar ej=new Ejecutar();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        a = new javax.swing.JTextField();
        Solucion = new javax.swing.JButton();
        b = new javax.swing.JTextField();
        c = new javax.swing.JTextField();
        d = new javax.swing.JTextField();
        e = new javax.swing.JTextField();
        f = new javax.swing.JTextField();
        g = new javax.swing.JTextField();
        h = new javax.swing.JTextField();
        i = new javax.swing.JTextField();
        j = new javax.swing.JTextField();
        k = new javax.swing.JTextField();
        l = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        rx = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ry = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        rz = new javax.swing.JLabel();
        Menu = new javax.swing.JButton();
        Limpiar = new javax.swing.JButton();
        Salir = new javax.swing.JButton();
        X5 = new javax.swing.JLabel();
        X6 = new javax.swing.JLabel();
        X7 = new javax.swing.JLabel();
        X8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 21)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Calculadora de Matrices");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Por metodo: Regla de Cramer");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, 30));

        a.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        a.setMargin(new java.awt.Insets(3, 3, 3, 3));
        getContentPane().add(a, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 40, 40));

        Solucion.setBackground(new java.awt.Color(0, 51, 102));
        Solucion.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Solucion.setForeground(new java.awt.Color(255, 255, 255));
        Solucion.setText("Resolver");
        Solucion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SolucionActionPerformed(evt);
            }
        });
        getContentPane().add(Solucion, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 230, 80, 25));
        Solucion.getAccessibleContext().setAccessibleDescription("");

        b.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(b, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 40, 40));

        c.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cActionPerformed(evt);
            }
        });
        getContentPane().add(c, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, 40, 40));

        d.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(d, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 40, 40));

        e.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(e, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 40, 40));

        f.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(f, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, 40, 40));

        g.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(g, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, 40, 40));

        h.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(h, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 40, 40));

        i.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        i.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iActionPerformed(evt);
            }
        });
        getContentPane().add(i, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, 40, 40));

        j.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(j, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, 40, 40));

        k.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        k.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kActionPerformed(evt);
            }
        });
        getContentPane().add(k, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, 40, 40));

        l.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(l, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 240, 40, 40));

        jLabel4.setFont(new java.awt.Font("Yu Gothic Light", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("X:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, -1, -1));

        rx.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rx.setForeground(new java.awt.Color(255, 255, 255));
        rx.setText("0");
        getContentPane().add(rx, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 90, 26));

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Y:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 340, -1, -1));

        ry.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ry.setForeground(new java.awt.Color(255, 255, 255));
        ry.setText("0");
        getContentPane().add(ry, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 342, 80, 20));

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Z:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 340, -1, -1));

        rz.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rz.setForeground(new java.awt.Color(255, 255, 255));
        rz.setText("0");
        getContentPane().add(rz, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 342, 90, 20));

        Menu.setBackground(new java.awt.Color(0, 51, 102));
        Menu.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Menu.setForeground(new java.awt.Color(255, 255, 255));
        Menu.setText("Menu");
        Menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuActionPerformed(evt);
            }
        });
        getContentPane().add(Menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 310, 80, 25));

        Limpiar.setBackground(new java.awt.Color(0, 51, 102));
        Limpiar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Limpiar.setForeground(new java.awt.Color(255, 255, 255));
        Limpiar.setText("Limpiar");
        Limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimpiarActionPerformed(evt);
            }
        });
        getContentPane().add(Limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 270, 80, 25));

        Salir.setBackground(new java.awt.Color(0, 51, 102));
        Salir.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Salir.setForeground(new java.awt.Color(255, 255, 255));
        Salir.setText("Salir");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });
        getContentPane().add(Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 350, 80, 25));

        X5.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        X5.setForeground(new java.awt.Color(255, 255, 255));
        X5.setText("X");
        getContentPane().add(X5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, -1, -1));

        X6.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        X6.setForeground(new java.awt.Color(255, 255, 255));
        X6.setText("Y");
        getContentPane().add(X6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, -1, -1));

        X7.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        X7.setForeground(new java.awt.Color(255, 255, 255));
        X7.setText("Z");
        getContentPane().add(X7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, -1, -1));

        X8.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        X8.setForeground(new java.awt.Color(255, 255, 255));
        X8.setText("B");
        getContentPane().add(X8, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, -1, -1));

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("El resultado es:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, -1, -1));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calculadora/fondo05.jpg"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void SolucionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SolucionActionPerformed
        ej.capturaIng();
        ej.imprimirIng();
    }//GEN-LAST:event_SolucionActionPerformed

    private void iActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iActionPerformed

    private void kActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kActionPerformed

    private void MenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuActionPerformed
        this.setVisible(false);
        Menu v=new Menu();
        v.setVisible(true);
        v.setTitle("Calculadora Matriz");        
    }//GEN-LAST:event_MenuActionPerformed

    private void LimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimpiarActionPerformed
        a.setText(null);
        b.setText(null);
        c.setText(null);
        d.setText(null);
        e.setText(null);
        f.setText(null);
        g.setText(null);
        h.setText(null);
        i.setText(null);
        j.setText(null);
        k.setText(null);
        l.setText(null);
        rx.setText("0");
        ry.setText("0");
        rz.setText("0");
    }//GEN-LAST:event_LimpiarActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
       System.exit(0);
    }//GEN-LAST:event_SalirActionPerformed

    private void cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cActionPerformed

    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PorTres().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Limpiar;
    private javax.swing.JButton Menu;
    private javax.swing.JButton Salir;
    private javax.swing.JButton Solucion;
    private javax.swing.JLabel X5;
    private javax.swing.JLabel X6;
    private javax.swing.JLabel X7;
    private javax.swing.JLabel X8;
    public static javax.swing.JTextField a;
    public static javax.swing.JTextField b;
    public static javax.swing.JTextField c;
    public static javax.swing.JTextField d;
    public static javax.swing.JTextField e;
    public static javax.swing.JTextField f;
    private javax.swing.JLabel fondo;
    public static javax.swing.JTextField g;
    public static javax.swing.JTextField h;
    public static javax.swing.JTextField i;
    public static javax.swing.JTextField j;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    public static javax.swing.JTextField k;
    public static javax.swing.JTextField l;
    public static javax.swing.JLabel rx;
    public static javax.swing.JLabel ry;
    public static javax.swing.JLabel rz;
    // End of variables declaration//GEN-END:variables
}
